### ISSUE TITLE
Out of range

### ISSUE THREAD

**Issue by dolorain** [ClaudiuGeorgiu/PlaystoreDownloader#11] opened 2018-03-27 08:13 UTC
When i using the command :
python3 download.py "com.madfingergames.legends"

report an error:

`Traceback (most recent call last):
  File "download.py", line 98, in <module>
    main()
  File "download.py", line 90, in main
    success = api.download(details['package_name'], downloaded_apk_file_path, download_obb=False)
  File "/data/PlaystoreDownloader/playstore/playstore.py", line 376, in download
    offer_type = details.docV2.offer[0].offerType
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range`

**Comment by ClaudiuGeorgiu** [comment] 2018-03-27 08:46
Hi @dolorain, unfortunately I'm not able to reproduce the issue, since I've tried to download that app and it worked for me. Are you using the latest version of the tool? What version of `protobuf` have you installed (I have `protobuf==3.4.0`)?

**Comment by dolorain** [comment] 2018-03-28 05:35
I have checked the version of the requirements.
```
Python 3.6.
Protobuf 3.4.0 (I just update to 3.5.2) .
And the lastest version of your pyhton program.
```
Perhaps this problem is caused by other things.
I will try to find the reason. If I find something, I will reply here.

**Comment by ClaudiuGeorgiu** [comment] 2018-03-28 07:56
I've just tried using the docker version (building it from scratch) and it also works. By the way, are you able to download the app when using your real device? What is the content of `details.docV2` when it throws the error?

**Comment by ClaudiuGeorgiu** [comment] 2018-04-24 13:52
I'm closing this for now, please reopen if you have further details.

**Closed by ClaudiuGeorgiu** 2018-04-24 13:52 UTC
